// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (id, name)
VALUES($1, $2)
RETURNING id, name
`

type CreateAuthorParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor, arg.ID, arg.Name)
	var i Author
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (id, created_at, updated_at, name, isbn)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, name, isbn
`

type CreateBookParams struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Name      string
	Isbn      pgtype.Text
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Isbn,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Isbn,
	)
	return i, err
}

const getAuthor = `-- name: GetAuthor :one
SELECT name 
FROM authors
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetAuthor(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, getAuthor, name)
	err := row.Scan(&name)
	return name, err
}

const linkBookAuthor = `-- name: LinkBookAuthor :one
INSERT INTO book_authors (book_id, author_id)
VALUES($1, $2)
RETURNING book_id, author_id
`

type LinkBookAuthorParams struct {
	BookID   pgtype.UUID
	AuthorID pgtype.UUID
}

func (q *Queries) LinkBookAuthor(ctx context.Context, arg LinkBookAuthorParams) (BookAuthor, error) {
	row := q.db.QueryRow(ctx, linkBookAuthor, arg.BookID, arg.AuthorID)
	var i BookAuthor
	err := row.Scan(&i.BookID, &i.AuthorID)
	return i, err
}
