// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookuse.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getAuthorBooks = `-- name: GetAuthorBooks :many
SELECT books.name,authors.name,isbn,books.created_at,books.updated_at,book_id,author_id FROM book_authors 
JOIN books ON book_authors.book_id = books.id
JOIN authors ON book_authors.author_id = author_id
WHERE authors.id = $1
`

type GetAuthorBooksRow struct {
	Name      string
	Name_2    string
	Isbn      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	BookID    uuid.UUID
	AuthorID  uuid.UUID
}

func (q *Queries) GetAuthorBooks(ctx context.Context, id uuid.UUID) ([]GetAuthorBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, getAuthorBooks, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuthorBooksRow
	for rows.Next() {
		var i GetAuthorBooksRow
		if err := rows.Scan(
			&i.Name,
			&i.Name_2,
			&i.Isbn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookID,
			&i.AuthorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBook = `-- name: GetBook :one
SELECT books.name,authors.name,isbn,books.created_at,books.updated_at,book_id FROM book_authors 
JOIN books ON book_authors.book_id = books.id
JOIN authors ON book_authors.author_id = author_id
WHERE books.id = $1
LIMIT 1
`

type GetBookRow struct {
	Name      string
	Name_2    string
	Isbn      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	BookID    uuid.UUID
}

func (q *Queries) GetBook(ctx context.Context, id uuid.UUID) (GetBookRow, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i GetBookRow
	err := row.Scan(
		&i.Name,
		&i.Name_2,
		&i.Isbn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BookID,
	)
	return i, err
}

const getMetaData = `-- name: GetMetaData :one
SELECT books.file_path, books.mime_type FROM books
JOIN book_authors ON book_authors.book_id = books.id
WHERE book_authors.api_key = $1
LIMIT 1
`

type GetMetaDataRow struct {
	FilePath string
	MimeType sql.NullString
}

func (q *Queries) GetMetaData(ctx context.Context, apiKey string) (GetMetaDataRow, error) {
	row := q.db.QueryRowContext(ctx, getMetaData, apiKey)
	var i GetMetaDataRow
	err := row.Scan(&i.FilePath, &i.MimeType)
	return i, err
}
