// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (id,created_at, updated_at, name)
VALUES($1, $2, $3, $4)
RETURNING id, created_at, updated_at, name
`

type CreateAuthorParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, createAuthor,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (id, created_at, updated_at, name, isbn)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, name, isbn
`

type CreateBookParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Isbn      sql.NullString
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Isbn,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Isbn,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, created_at, updated_at, name
FROM authors
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetAuthor(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, name)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const linkBookAuthor = `-- name: LinkBookAuthor :one
INSERT INTO book_authors (book_id, author_id)
VALUES($1, $2)
RETURNING book_id, author_id, api_key
`

type LinkBookAuthorParams struct {
	BookID   uuid.UUID
	AuthorID uuid.UUID
}

func (q *Queries) LinkBookAuthor(ctx context.Context, arg LinkBookAuthorParams) (BookAuthor, error) {
	row := q.db.QueryRowContext(ctx, linkBookAuthor, arg.BookID, arg.AuthorID)
	var i BookAuthor
	err := row.Scan(&i.BookID, &i.AuthorID, &i.ApiKey)
	return i, err
}

const unlinkBook = `-- name: UnlinkBook :exec
DELETE FROM book_authors WHERE book_id = $1
`

func (q *Queries) UnlinkBook(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, unlinkBook, bookID)
	return err
}
