// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookuse.sql

package database

import (
	"context"
)

const getAuthorBook = `-- name: GetAuthorBook :many
SELECT books.name,authors.name,api_key FROM book_authors 
JOIN books ON book_authors.book_id = books.id
JOIN authors ON book_authors.author_id = author_id
WHERE authors.name = $1
`

type GetAuthorBookRow struct {
	Name   string
	Name_2 string
	ApiKey string
}

func (q *Queries) GetAuthorBook(ctx context.Context, name string) ([]GetAuthorBookRow, error) {
	rows, err := q.db.QueryContext(ctx, getAuthorBook, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuthorBookRow
	for rows.Next() {
		var i GetAuthorBookRow
		if err := rows.Scan(&i.Name, &i.Name_2, &i.ApiKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBook = `-- name: GetBook :many
SELECT books.name,authors.name,api_key FROM book_authors 
JOIN books ON book_authors.book_id = books.id
JOIN authors ON book_authors.author_id = author_id
WHERE books.name = $1
LIMIT 1
`

type GetBookRow struct {
	Name   string
	Name_2 string
	ApiKey string
}

func (q *Queries) GetBook(ctx context.Context, name string) ([]GetBookRow, error) {
	rows, err := q.db.QueryContext(ctx, getBook, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookRow
	for rows.Next() {
		var i GetBookRow
		if err := rows.Scan(&i.Name, &i.Name_2, &i.ApiKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
