// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookuse.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getAuthorBooks = `-- name: GetAuthorBooks :many
SELECT 
    books.id,
    books.name AS book_name,
    COALESCE(authors.name, '') AS author_name,
    books.isbn,
    books.file_path,
    books.mime_type,
    books.page_count,
    books.producer,
    books.subject,
    books.pdf_version,
    books.created_at,
    books.updated_at
FROM book_authors 
JOIN books ON book_authors.book_id = books.id
JOIN authors ON book_authors.author_id = authors.id
WHERE authors.id = $1
`

type GetAuthorBooksRow struct {
	ID         uuid.UUID
	BookName   string
	AuthorName string
	Isbn       sql.NullString
	FilePath   string
	MimeType   sql.NullString
	PageCount  sql.NullInt32
	Producer   sql.NullString
	Subject    sql.NullString
	PdfVersion sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) GetAuthorBooks(ctx context.Context, id uuid.UUID) ([]GetAuthorBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, getAuthorBooks, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuthorBooksRow
	for rows.Next() {
		var i GetAuthorBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.BookName,
			&i.AuthorName,
			&i.Isbn,
			&i.FilePath,
			&i.MimeType,
			&i.PageCount,
			&i.Producer,
			&i.Subject,
			&i.PdfVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBook = `-- name: GetBook :one
SELECT 
    books.id,
    books.name AS book_name,
    COALESCE(authors.name, '') AS author_name,
    books.isbn,
    books.file_path,
    books.mime_type,
    books.page_count,
    books.producer,
    books.subject,
    books.pdf_version,
    books.created_at,
    books.updated_at
FROM books
LEFT JOIN book_authors ON books.id = book_authors.book_id
LEFT JOIN authors ON book_authors.author_id = authors.id
WHERE books.id = $1
LIMIT 1
`

type GetBookRow struct {
	ID         uuid.UUID
	BookName   string
	AuthorName string
	Isbn       sql.NullString
	FilePath   string
	MimeType   sql.NullString
	PageCount  sql.NullInt32
	Producer   sql.NullString
	Subject    sql.NullString
	PdfVersion sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) GetBook(ctx context.Context, id uuid.UUID) (GetBookRow, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i GetBookRow
	err := row.Scan(
		&i.ID,
		&i.BookName,
		&i.AuthorName,
		&i.Isbn,
		&i.FilePath,
		&i.MimeType,
		&i.PageCount,
		&i.Producer,
		&i.Subject,
		&i.PdfVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMetaData = `-- name: GetMetaData :one
SELECT file_path, mime_type FROM books
WHERE id = $1
LIMIT 1
`

type GetMetaDataRow struct {
	FilePath string
	MimeType sql.NullString
}

func (q *Queries) GetMetaData(ctx context.Context, id uuid.UUID) (GetMetaDataRow, error) {
	row := q.db.QueryRowContext(ctx, getMetaData, id)
	var i GetMetaDataRow
	err := row.Scan(&i.FilePath, &i.MimeType)
	return i, err
}
