// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Author struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type Book struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Isbn      sql.NullString
	FilePath  string
	MimeType  sql.NullString
}

type BookAuthor struct {
	BookID   uuid.UUID
	AuthorID uuid.UUID
	ApiKey   string
}

type Secret struct {
	UserID   uuid.UUID
	PassHash string
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	FirstName string
	LastName  string
	Email     sql.NullString
	PhNo      sql.NullString
	Role      sql.NullString
}
