// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, first_name, last_name, ph_no, email)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, first_name, last_name, email, ph_no, role
`

type CreateUserParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	FirstName string
	LastName  string
	PhNo      sql.NullString
	Email     sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FirstName,
		arg.LastName,
		arg.PhNo,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhNo,
		&i.Role,
	)
	return i, err
}

const linkHash = `-- name: LinkHash :exec
INSERT INTO secrets (user_id, pass_hash)
VALUES($1, $2)
`

type LinkHashParams struct {
	UserID   uuid.UUID
	PassHash string
}

func (q *Queries) LinkHash(ctx context.Context, arg LinkHashParams) error {
	_, err := q.db.ExecContext(ctx, linkHash, arg.UserID, arg.PassHash)
	return err
}
