// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usersuse.sql

package database

import (
	"context"
	"database/sql"
)

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, first_name, last_name, email, ph_no, role
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhNo,
		&i.Role,
	)
	return i, err
}
